Eproject/Eproject/Models/Agent.cs
using System.ComponentModel.DataAnnotations;

namespace Eproject.Models
{
    public class Agent
    {
        public int AgentId { get; set; }
        [Display(Name = "User Name")]
        [Required]
        [MinLength(3, ErrorMessage = "Min 3 Chr Required"), MaxLength(50)]
        public string Username { get; set; }
        [DataType(DataType.Password)]
        [Required]
        [MinLength(3, ErrorMessage = "Min 3 Chr Required"), MaxLength(50)]
        public string Password { get; set; }
        [DataType(DataType.Password)]
        [Required]
        [MinLength(3, ErrorMessage = "Min 3 Chr Required"), MaxLength(50)]
        [Display(Name = "Confirm Password")]
        [Compare("Password", ErrorMessage = "Password Not Match")]
        public string CPassword { get; set; }
        [Required]
        [MinLength(3, ErrorMessage = "Min 3 Chr Required"), MaxLength(50)]
        public string Email { get; set; }
        public int UserId { get; set; }
    }
}

Eproject/Eproject/Controllers/AgentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Eproject.Models;

namespace Eproject.Controllers
{
    public class AgentsController : Controller
    {
        private readonly Dbs _context;

        public AgentsController(Dbs context)
        {
            _context = context;
        }

        // GET: Agents
        public async Task<IActionResult> Index()
        {
              return _context.AgentLogins != null ?
              View(await _context.AgentLogins.ToListAsync()) :
              Problem("Entity set 'Dbs.AgentLogins' is null.");
        }

        // GET: Agents/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.AgentLogins == null)
            {
                return NotFound();
            }

            var agent = await _context.AgentLogins
                .FirstOrDefaultAsync(m => m.AgentId == id);
            if (agent == null)
            {
                return NotFound();
            }

            return View(agent);
        }

        // GET: Agents/Create
        public IActionResult Create()
        {
            var id = HttpContext.Session.GetInt32("ID");

            if (id != null)
            {
                var e = HttpContext.Session.GetString("ID");
                ViewBag.id = id;
                return View();
            }
            else
            {
                return RedirectToAction("UserLogin", "Home");
            }
        }

        // POST: Agents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Agent agent)
        {
            if (ModelState.IsValid)
            {
                HttpContext.Session.SetString("a", agent.Email);
                _context.Add(agent);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(agent);
        }
        //public IActionResult AgentLogin()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public ActionResult AgentLogin(Agent lg)
        //{
        //    var x = from a in _context.UserLogins
        //            where a.Email.Equals(lg.Email) && a.Password.Equals(lg.Password)
        //            select a;
        //    if (x.Any())
        //    {
        //        HttpContext.Session.SetString("u", lg.Email);
        //        return RedirectToAction("Index", "Home");
        //    }
        //    else
        //    {
        //        ViewBag.m = "Wrong Email Or Password";
        //    }
        //    return View();
        //}

        // GET: Agents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.AgentLogins == null)
            {
                return NotFound();
            }

            var agent = await _context.AgentLogins.FindAsync(id);
            if (agent == null)
            {
                return NotFound();
            }
            return View(agent);
        }

        // POST: Agents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AgentId,Username,Password,CPassword,Email")] Agent agent)
        {
            if (id != agent.AgentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(agent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AgentExists(agent.AgentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(agent);
        }

        // GET: Agents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.AgentLogins == null)
            {
                return NotFound();
            }

            var agent = await _context.AgentLogins
                .FirstOrDefaultAsync(m => m.AgentId == id);
            if (agent == null)
            {
                return NotFound();
            }

            return View(agent);
        }

        // POST: Agents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.AgentLogins == null)
            {
                return Problem("Entity set 'Dbs.AgentLogins'  is null.");
            }
            var agent = await _context.AgentLogins.FindAsync(id);
            if (agent != null)
            {
                _context.AgentLogins.Remove(agent);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AgentExists(int id)
        {
          return (_context.AgentLogins?.Any(e => e.AgentId == id)).GetValueOrDefault();
        }
    }
}

Eproject/Eproject/Views/Agents/Create.cshtml
@model Eproject.Models.Agent

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Agent Profile</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPassword" class="control-label"></label>
                <input asp-for="CPassword" class="form-control" />
                <span asp-validation-for="CPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="UserId" type="hidden" value="@ViewBag.id" class="single-input" />

            <div class="form-group mt-2">
                <input type="submit" value="Create" class="btn btn-primary" />
@*                <a class="btn btn-danger" asp-area="" asp-controller="Agents" asp-action="AgentLogin">Already Account SignIn</a>
*@            </div>
        </form>
    </div>
</div>

Eproject/Eproject/Views/Agents/Delete.cshtml
@model Eproject.Models.Agent

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Agent</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPassword)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPassword)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AgentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Eproject/Eproject/Views/Agents/Details.cshtml
@model Eproject.Models.Agent

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Agent</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPassword)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPassword)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.AgentId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Eproject/Eproject/Views/Agents/Edit.cshtml
@model Eproject.Models.Agent

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Agent</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AgentId" />
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPassword" class="control-label"></label>
                <input asp-for="CPassword" class="form-control" />
                <span asp-validation-for="CPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Eproject/Eproject/Views/Agents/Index.cshtml
@model IEnumerable<Eproject.Models.Agent>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CPassword)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CPassword)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.AgentId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.AgentId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.AgentId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>